version: '3'
services:
  app:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: TwitchContainer
    volumes:
      - ./bot:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
    - RUNNING_IN_DOCKER=true
    restart: always

  postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin123
        POSTGRES_DB: twitch_analysis
      volumes:
        - ./database/postgres-db-volume:/var/lib/postgresql/data
        - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "admin", "-d", "twitch_analysis"]
        interval: 10s
        retries: 5
        start_period: 5s
      restart: always
      container_name: postgres
      ports:
        - 5432:5432

  scoreboard:
    build:
      context: ./scoreboard
      dockerfile: Dockerfile
    container_name: Scoreboard
    volumes:
      - ./scoreboard:/app
    ports:
      - 8501:8501 # Assuming you want to run the scoreboard on a different port
    depends_on:
      - postgres
    restart: always
    environment:
    - RUNNING_IN_DOCKER=true

volumes:
  postgres-db-volume:
